name: Generate coverage badges

on:
  workflow_dispatch:
  pull_request:
    branches: 
      - "main"
    types: 
      - closed

jobs:
  badges:
#    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: show run id
        run: | 
          echo "run id = $GITHUB_RUN_ID"
          echo "commit hash = $GITHUB_SHA"

      - uses: actions/download-artifact@v4
        with:
          name: jacoco-report-${GITHUB_SHA}
          path: target/site/jacoco/
          run-id: $GITHUB_RUN_ID
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate JaCoCo Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true

      - name: Log coverage percentage
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
          echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"

      - name: Commit and push the badge (if it changed)
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'commit badge'
          add: '*.svg'
