name: Java CI with Maven

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "main"
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: show run id
        run: | 
          echo "run id = $GITHUB_RUN_ID"
          echo "commit hash = $GITHUB_SHA"

      - uses: actions/setup-java@v4
        with:
          java-version: '17.0.11'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B test

      - name: Upload JaCoCo coverage report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report-$GITHUB_SHA
          path: target/site/jacoco/
