name: Java CI with Maven

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17.0.11'
          distribution: 'temurin'
      - name: Run the Maven verify phase
        run: mvn --batch-mode --update-snapshots verify
